version: "3.8"

services:
  bot:
    image: dnn_bot:latest
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - conf.env
    command: sh -c "alembic upgrade head && python run.py"
    depends_on:
      - db

  db:
    image: postgres:14.2-bullseye
    env_file:
      - conf.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
    external: false
